### ISSUE TITLE
Mise à jour de 6.5.6 à 6.5.7

### ISSUE THREAD

**Issue by gd5t** [pelsql/YourSqlDba#2]
Msg 208, Niveau 16, État 1, Procédure DetailQueriesStats, Ligne 1285
Invalid object name 'master.sys.dm_exec_Function_stats'.

**Comment by gd5t** [comment]
[sys.dm_exec_function_stats (Transact-SQL)](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-exec-function-stats-transact-sql)
THIS TOPIC APPLIES TO: SQL Server (starting with 2016)

**Comment by pelsql** [comment]
I will add conditional code to create optionally this object only if Server is SQL2016

**Comment by pelsql** [comment]
This is done. YourSqlDba version changes from version 6.5.7 to 6.5.7.1.  I tested the script on SQL2014 and SQL2016.  I'm not yet very familiar with Github, so it took me some time to get it set.
